# Generated by Django 3.0.4 on 2020-03-20 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
                ('publicated', models.BooleanField(db_index=True, default=True, verbose_name='Опубликовано?')),
            ],
            options={
                'permissions': (('can_views_prof_news', 'Can view professional news'),),
            },
        ),
        migrations.CreateModel(
            name='NewsContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(choices=[('ru', 'Russian')], db_index=True, max_length=2, verbose_name='Язык')),
                ('title', models.CharField(max_length=512, verbose_name='Заглавие')),
                ('teaser', models.CharField(max_length=512, verbose_name='Тизер')),
                ('content', models.TextField(verbose_name='Содержание новости')),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='professionals_news.News')),
            ],
            options={
                'unique_together': {('news', 'lang')},
            },
        ),
    ]
