# Generated by Django 3.0.4 on 2020-03-27 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ask_librarian', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='fio',
            field=models.CharField(blank=True, default='', max_length=128, verbose_name='ФИО'),
        ),
    ]
