# Generated by Django 3.0.5 on 2020-04-14 22:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ask_librarian', '0002_auto_20200327_1326'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='update_date',
            field=models.DateTimeField(auto_now=True, db_index=True, verbose_name='Дата обновления'),
        ),
        migrations.CreateModel(
            name='StatusJournal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(0, 'Новый'), (1, 'Готов'), (2, 'В обработке')], db_index=True, verbose_name='Статус')),
                ('message', models.TextField(blank=True, max_length=10240)),
                ('create_date', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ask_librarian.Question')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь сменивший статус')),
            ],
        ),
    ]
