# Generated by Django 3.0.5 on 2020-04-14 23:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ask_librarian', '0003_auto_20200414_2214'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionTarget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=512, verbose_name='Название')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.AlterField(
            model_name='question',
            name='category',
            field=models.ForeignKey(help_text='Укажите тематику, к которой относиться вопрос', null=True, on_delete=django.db.models.deletion.PROTECT, to='ask_librarian.Category', verbose_name='Тематика'),
        ),
        migrations.AlterField(
            model_name='question',
            name='email',
            field=models.EmailField(blank=True, max_length=256, verbose_name='email'),
        ),
        migrations.AddField(
            model_name='question',
            name='question_target',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='ask_librarian.QuestionTarget', verbose_name='Цель запроса'),
        ),
    ]
