# Generated by Django 3.0.5 on 2020-04-16 21:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ask_librarian', '0004_auto_20200414_2323'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=512, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Образование',
                'verbose_name_plural': 'Виды образования',
                'ordering': ['title'],
            },
        ),
        migrations.AlterModelOptions(
            name='questiontarget',
            options={'ordering': ['title'], 'verbose_name': 'Цель вопроса', 'verbose_name_plural': 'Цели вопросов'},
        ),
        migrations.AlterField(
            model_name='question',
            name='answer',
            field=models.TextField(blank=True, max_length=50000, verbose_name='Ответ'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_target',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ask_librarian.QuestionTarget', verbose_name='Цель запроса'),
        ),
        migrations.AlterField(
            model_name='question',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='question',
            name='education',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ask_librarian.Education', verbose_name='Образование'),
        ),
    ]
