# Generated by Django 3.0.5 on 2022-12-06 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ask_librarian', '0006_auto_20221206_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='category',
            field=models.ForeignKey(help_text='Укажите тематику, к которой относится вопрос', null=True, on_delete=django.db.models.deletion.PROTECT, to='ask_librarian.Category', verbose_name='Тематика *'),
        ),
        migrations.AlterField(
            model_name='question',
            name='city',
            field=models.CharField(max_length=64, verbose_name='Город *'),
        ),
        migrations.AlterField(
            model_name='question',
            name='education',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='ask_librarian.Education', verbose_name='Образование *'),
        ),
        migrations.AlterField(
            model_name='question',
            name='email',
            field=models.EmailField(max_length=256, verbose_name='email *'),
        ),
        migrations.AlterField(
            model_name='question',
            name='fio',
            field=models.CharField(default='', max_length=128, verbose_name='ФИО *'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question',
            field=models.TextField(max_length=2048, verbose_name='Вопрос *'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_target',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='ask_librarian.QuestionTarget', verbose_name='Цель запроса *'),
        ),
    ]
