# Generated by Django 3.0.4 on 2020-03-20 12:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(db_index=True, verbose_name='Дата начала')),
                ('end_date', models.DateTimeField(db_index=True, verbose_name='Дата окончания')),
                ('address', models.CharField(blank=True, max_length=512, verbose_name='Место проведения')),
                ('active', models.BooleanField(db_index=True, default=True, verbose_name='Активно')),
                ('create_date', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'мероприятие',
                'verbose_name_plural': 'мероприятия',
            },
        ),
        migrations.CreateModel(
            name='FavoriteEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.Event', verbose_name='Мероприятие')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'отмеченное мероприятие',
                'verbose_name_plural': 'отмеченные мероприятия',
            },
        ),
        migrations.CreateModel(
            name='EventRemember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remember_date', models.DateField(blank=True, null=True, verbose_name='Дата напоминания')),
                ('remember_system', models.IntegerField(default=0, verbose_name='Система напоминания (0-email, 1-sms)')),
                ('favorite_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.FavoriteEvent', verbose_name='Избранное событие')),
            ],
        ),
        migrations.CreateModel(
            name='EventComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=1024, verbose_name='Текст комментария (макс. 1024 символа)')),
                ('post_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата отправления')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.Event', verbose_name='Мероприятие')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'комментарий',
                'verbose_name_plural': 'комментарии',
            },
        ),
        migrations.CreateModel(
            name='EventContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(choices=[('ru', 'Russian')], db_index=True, max_length=2, verbose_name='Язык')),
                ('title', models.CharField(max_length=512, verbose_name='Заглавие')),
                ('teaser', models.CharField(max_length=512, verbose_name='Тизер')),
                ('content', models.TextField(verbose_name='Описание события')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.Event')),
            ],
            options={
                'unique_together': {('event', 'lang')},
            },
        ),
    ]
