# Generated by Django 3.0.5 on 2021-03-22 18:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgeCategory',
            fields=[
                ('age', models.IntegerField(help_text='Укажите возраст, начиная с которого, можно посещать события.', primary_key=True, serialize=False, verbose_name='Возраст (лет)')),
            ],
            options={
                'verbose_name': 'Возрастная категория',
                'verbose_name_plural': 'Возрастные категории',
                'ordering': ['age'],
            },
        ),
        migrations.CreateModel(
            name='EventParticipant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=256, verbose_name='Фамилия')),
                ('first_name', models.CharField(max_length=256, verbose_name='Имя Отчество')),
                ('reader_id', models.CharField(max_length=256, verbose_name='№ читательского билета')),
                ('email', models.EmailField(max_length=256, verbose_name='Email')),
                ('create_date', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Участник мероприятия',
                'verbose_name_plural': 'Участники мероприятий',
            },
        ),
        migrations.AddField(
            model_name='event',
            name='keywords',
            field=models.CharField(blank=True, help_text='Через запятую', max_length=1024, verbose_name='Ключевые слова'),
        ),
        migrations.AlterUniqueTogether(
            name='favoriteevent',
            unique_together={('user', 'event')},
        ),
        migrations.CreateModel(
            name='EventParticipationReminder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remind_date', models.DateTimeField(db_index=True, verbose_name='Время напоминания')),
                ('type', models.CharField(choices=[('email', 'по электронной почте'), ('sms', 'sms')], default='email', max_length=64, verbose_name='Тип напоминияния')),
                ('is_sent', models.BooleanField(db_index=True, default=False, verbose_name='Отправлено')),
                ('created', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Дата создания')),
                ('event_participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.EventParticipant', verbose_name='Участник')),
            ],
            options={
                'verbose_name': 'Напоминания об участии',
                'verbose_name_plural': 'Напоминания об участии',
            },
        ),
        migrations.AddField(
            model_name='eventparticipant',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.Event', verbose_name='Мероприятие'),
        ),
        migrations.AddField(
            model_name='eventparticipant',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('code', models.SlugField(help_text='Разрешены латинские буквы, знаки _ и -', max_length=128, primary_key=True, serialize=False, verbose_name='Код категории')),
                ('title', models.CharField(db_index=True, max_length=1024, verbose_name='Название')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='events.Category', verbose_name='Родительская категория')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['title'],
            },
        ),
        migrations.AddField(
            model_name='event',
            name='age_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='events.AgeCategory', verbose_name='Возрастная категория'),
        ),
        migrations.AddField(
            model_name='event',
            name='category',
            field=models.ManyToManyField(blank=True, to='events.Category', verbose_name='Категории'),
        ),
        migrations.AlterUniqueTogether(
            name='eventparticipant',
            unique_together={('user', 'event')},
        ),
    ]
