# Generated by Django 3.0.5 on 2021-03-26 14:54

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=512, verbose_name='Название места')),
                ('address', models.CharField(blank=True, max_length=512, verbose_name='Адрес')),
                ('contacts', models.TextField(blank=True, max_length=1024, verbose_name='Контакты')),
                ('geo_latitude', models.FloatField(default=0, verbose_name='Гео широта')),
                ('geo_longitude', models.FloatField(default=0, verbose_name='Гео долгота')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='address_parent', to='events.Address')),
            ],
            options={
                'verbose_name': 'Адрес',
                'verbose_name_plural': 'Адреса',
                'ordering': ['title'],
            },
        ),
        migrations.AddField(
            model_name='event',
            name='address_reference',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='events.Address', verbose_name='Место проведения из справочника'),
        ),
    ]
