# Generated by Django 3.0.5 on 2021-04-13 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='need_registration',
            field=models.BooleanField(default=False, verbose_name='Требуется регистрация'),
        ),
    ]
