# Generated by Django 3.0.5 on 2021-05-17 13:34

from django.db import migrations, models
import events.models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_need_registration'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='avatar',
            field=models.ImageField(blank=True, upload_to=events.models.upload_avatar_handler, verbose_name='Аватарка'),
        ),
    ]
