# Generated by Django 3.0.5 on 2021-03-22 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20210322_1815'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='translation_html',
            field=models.TextField(blank=True, max_length=10240, verbose_name='HTML код плеера для трансляций или воспроизведения'),
        ),
    ]
