# Generated by Django 3.0.5 on 2021-03-23 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_event_translation_html'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=512, verbose_name='Название места')),
                ('address', models.CharField(max_length=512, verbose_name='Адрес')),
                ('contacts', models.TextField(max_length=1024, verbose_name='Контакты')),
            ],
            options={
                'verbose_name': 'Адрес',
                'verbose_name_plural': 'Адреса',
                'ordering': ['title'],
            },
        ),
        migrations.AddField(
            model_name='event',
            name='address_reference',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='events.Address', verbose_name='Место проведения из справочника'),
        ),
    ]
