# Generated by Django 3.0.5 on 2021-03-23 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_auto_20210323_1426'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='geo_latitude',
            field=models.FloatField(default=0, verbose_name='Гео широта'),
        ),
        migrations.AddField(
            model_name='address',
            name='geo_longitude',
            field=models.FloatField(default=0, verbose_name='Гео долгота'),
        ),
    ]
