# Generated by Django 3.0.4 on 2020-03-25 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
                ('type', models.IntegerField(choices=[(0, 'Новости ЧОУНБ'), (1, 'Новости библиотек области'), (2, 'Общие')], db_index=True, default=(0, 'Публичные'), verbose_name='Вид новостей')),
                ('publicated', models.BooleanField(db_index=True, default=True, verbose_name='Опубликовано?')),
                ('avatar_img_name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='NewsContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(choices=[('ru', 'Russian')], db_index=True, max_length=2, verbose_name='Язык')),
                ('title', models.CharField(max_length=512, verbose_name='Заглавие')),
                ('teaser', models.CharField(help_text='Краткое описание новости', max_length=512, verbose_name='Тизер')),
                ('content', models.TextField(verbose_name='Содержание новости')),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.News')),
            ],
            options={
                'unique_together': {('news', 'lang')},
            },
        ),
    ]
