# Generated by Django 3.0.5 on 2021-03-25 19:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_username', models.CharField(db_index=True, max_length=255, verbose_name='Имя пользователя во внешней системе')),
                ('auth_source', models.CharField(db_index=True, max_length=32, verbose_name='Идентфикатор источника аутенификации')),
                ('attributes', models.TextField(max_length=10240, verbose_name='Атрибуты пользователя в формате JSON')),
                ('update', models.DateTimeField(auto_now=True, db_index=True)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Связь с пользователем')),
            ],
            options={
                'unique_together': {('external_username', 'auth_source')},
            },
        ),
    ]
