# Generated by Django 3.0.4 on 2020-03-20 12:11

from django.db import migrations, models
import django.db.models.deletion
import gallery.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=64, unique=True, verbose_name='Slug')),
                ('title', models.CharField(max_length=512, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('public', models.BooleanField(db_index=True, default=False, verbose_name='Опубликован')),
                ('create_date', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
            ],
            options={
                'ordering': ['-create_date'],
                'permissions': (('public_album', 'Can public album'),),
            },
        ),
        migrations.CreateModel(
            name='AlbumImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(max_length=512, upload_to=gallery.models.image_file_name, verbose_name='Файл с изображением')),
                ('comments', models.CharField(blank=True, max_length=512, verbose_name='Коментарии к изображению')),
                ('create_date', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gallery.Album')),
            ],
        ),
    ]
