# Generated by Django 3.0.5 on 2020-04-16 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_form', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactrequest',
            name='message',
            field=models.TextField(blank=True, default='', max_length=1024, verbose_name='Сообщение'),
        ),
    ]
