# Generated by Django 3.0.4 on 2020-03-23 13:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ViewDocLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_id', models.CharField(db_index=True, max_length=32)),
                ('collection_id', models.CharField(db_index=True, max_length=64, null=True)),
                ('view_date_time', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SearchLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('params', models.TextField(blank=True, max_length=2048, verbose_name='Параметры поиска')),
                ('total', models.BigIntegerField(default=0, verbose_name='Найдено записей')),
                ('in_results', models.BooleanField(default=False, verbose_name='Уточнение результатов')),
                ('session_id', models.CharField(db_index=True, max_length=64, verbose_name='Идентификатор сесии')),
                ('date_time', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('params_crc32', models.IntegerField(db_index=True, default=0, verbose_name='CRC32 json-строки параметров запроса')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DetailLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_id', models.CharField(db_index=True, max_length=64)),
                ('action', models.IntegerField(db_index=True, default=0, verbose_name='Действие')),
                ('session_id', models.CharField(db_index=True, max_length=64, verbose_name='Идентификатор сесии')),
                ('attrs', models.TextField(blank=True, max_length=10240, verbose_name='JSON атрибуты')),
                ('date_time', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
