# Generated by Django 3.0.4 on 2020-03-20 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variant', models.IntegerField(choices=[(0, 'Персоналия'), (1, 'Организация'), (2, 'Мероприятие'), (3, 'Географический объект'), (4, 'Тема')], db_index=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ImportantDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, help_text='Если неизвестен день или месяц даты, то выставлять 01. 01.01.1061', verbose_name='Дата события')),
                ('count_day', models.BooleanField(db_index=True, default=True, verbose_name='Учитывать день даты')),
                ('count_month', models.BooleanField(db_index=True, default=True, verbose_name='Учитывать месяц даты')),
                ('count_year', models.BooleanField(db_index=True, default=True, verbose_name='Учитывать год даты')),
                ('fio', models.CharField(blank=True, max_length=512, null=True, verbose_name='ФИО персоналии')),
                ('org_title', models.CharField(blank=True, max_length=512, null=True, verbose_name='Название организации')),
                ('event_title', models.CharField(blank=True, max_length=512, null=True, verbose_name='Название мероприятия')),
                ('geo_title', models.CharField(blank=True, max_length=512, null=True, verbose_name='Наименование геогр. объекта')),
                ('theme', models.CharField(blank=True, max_length=512, null=True, verbose_name='Тема')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('literature', models.TextField(blank=True, verbose_name='Литература')),
                ('create_date', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
                ('type', models.ManyToManyField(to='cid.Type', verbose_name='Тип события')),
            ],
        ),
    ]
