# Generated by Django 3.0.4 on 2020-03-20 12:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Records',
            fields=[
                ('id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('original_id', models.CharField(max_length=32)),
                ('hash', models.CharField(max_length=32)),
                ('source', models.CharField(max_length=32)),
                ('record_scheme', models.CharField(max_length=32)),
                ('format', models.CharField(max_length=32)),
                ('session_id', models.BigIntegerField()),
                ('create_date', models.DateTimeField()),
                ('update_date', models.DateTimeField()),
                ('deleted', models.SmallIntegerField()),
            ],
            options={
                'db_table': 'records',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RecordsContent',
            fields=[
                ('record', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='search.Records')),
                ('content', models.TextField()),
            ],
            options={
                'db_table': 'records_content',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SavedRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_request', models.CharField(max_length=1024)),
                ('add_time', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_request_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
