# Generated by Django 3.0.5 on 2021-04-29 20:55

from django.db import migrations
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('subscribe', '0002_letter_to_subscriber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscribe',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='subscribe.Subscribe'),
        ),
    ]
