# Generated by Django 3.0.4 on 2020-03-20 12:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ZCatalog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='Название каталога')),
                ('latin_title', models.SlugField(unique=True, verbose_name='Название каталога (латинскими буквами)')),
                ('description', models.TextField(verbose_name='Описание каталога')),
                ('help', models.TextField(blank=True, null=True, verbose_name='Справка для каталога')),
                ('default_lang', models.CharField(choices=[('rus', 'Русский'), ('eng', 'English')], default=('rus', 'Русский'), max_length=10, verbose_name='Язык каталога по умолчанию')),
                ('url', models.URLField(help_text='Например: http://consortium.ruslan.ru/cgi-bin/zgate', verbose_name='URL АРМ Читателя')),
                ('xml', models.CharField(help_text='Нужно уточнить у администратора', max_length=256, verbose_name='Имя XML файла')),
                ('xsl', models.CharField(help_text='Нужно уточнить у администратора', max_length=256, verbose_name='Имя XSL файла')),
                ('can_search', models.BooleanField(default=True, help_text='Доступ к каталогу для поиска', verbose_name='Возможность поиска')),
                ('can_order_auth_only', models.BooleanField(default=True, help_text='Заказ в каталоге возможен только если пользователь авторизирован на портале', verbose_name='Возможность заказа в каталоге только авторизированным пользователям на портале')),
                ('can_order_copy', models.BooleanField(verbose_name='Возможность заказа копии документа')),
                ('can_order_document', models.BooleanField(verbose_name='Возможность заказа документа во временное пользование')),
                ('can_reserve', models.BooleanField(verbose_name='Возможность  бронирования документа')),
            ],
            options={
                'verbose_name': 'Каталог (АРМ читателя)',
                'verbose_name_plural': 'Каталоги (АРМ читателя)',
            },
        ),
        migrations.CreateModel(
            name='SearchRequestLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_id', models.CharField(db_index=True, max_length=32, verbose_name='Идентификатор запроса')),
                ('use', models.CharField(db_index=True, max_length=32, verbose_name='Точка доступа')),
                ('normalize', models.CharField(db_index=True, max_length=256, verbose_name='Нормализованный терм')),
                ('not_normalize', models.CharField(db_index=True, max_length=256, verbose_name='Ненормализованный терм')),
                ('datetime', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('catalog', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='zgate.ZCatalog')),
            ],
        ),
        migrations.CreateModel(
            name='SavedRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zurls', models.CharField(max_length=2048, verbose_name='Список баз данных для поиска')),
                ('query', models.CharField(max_length=1024, verbose_name='Запрос АРМ Читателя')),
                ('human_query', models.CharField(blank=True, max_length=1024, verbose_name='Расшифровка запроса')),
                ('add_date', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('zcatalog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zgate.ZCatalog')),
            ],
        ),
        migrations.CreateModel(
            name='SavedDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_id', models.CharField(db_index=True, max_length=32, verbose_name='Идентификатор сессии (md5) или имя пользователя')),
                ('document', models.TextField(verbose_name='Тело документа (xml rusmarc)')),
                ('comments', models.CharField(blank=True, max_length=2048, verbose_name='Комментарий к документу')),
                ('add_date', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата добваления документа')),
                ('expiry_date', models.DateTimeField(db_index=True, null=True, verbose_name='Дата когда документ удалится')),
                ('full_document', models.TextField(blank=True, null=True, verbose_name='Полная запись на документ')),
                ('short_document', models.TextField(blank=True, null=True, verbose_name='Краткая запись на документ')),
                ('zcatalog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zgate.ZCatalog')),
            ],
        ),
    ]
