# Generated by Django 3.0.4 on 2020-03-20 12:11

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Forum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Maximum 255 simbols', max_length=255, verbose_name='Title')),
                ('slug', models.SlugField(help_text='Small latin letter, "-" and "_"', unique=True, verbose_name='Slug')),
                ('description', models.CharField(help_text='Maximum 1024 simbols', max_length=1024, verbose_name='Description')),
                ('ordering', models.IntegerField(db_index=True, default=0, help_text='Order in forums list', verbose_name='Ordering')),
                ('closed', models.BooleanField(db_index=True, default=False, help_text='If forum is closed, users can not create topics', verbose_name='Closed')),
                ('deleted', models.BooleanField(db_index=True, default=False, verbose_name='Deleted')),
            ],
            options={
                'ordering': ['ordering'],
                'permissions': (('can_views_forums', 'Can view forums'), ('can_close_forums', 'Can close forum'), ('can_view_topics', 'Can view topics in forum'), ('can_create_topics', 'Can create topics in forum'), ('can_change_topics', 'Can change topics in forum'), ('can_delete_topics', 'Can delete topics in forum'), ('can_close_topics', 'Can close all topics in forum'), ('can_close_own_topics', 'Can close own topics in forum'), ('can_hide_topics', 'Can hide topics in forum')),
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(help_text='Maximum 255 simbols', max_length=255, verbose_name='Subject')),
                ('created', models.DateTimeField(db_index=True, default=datetime.datetime.now, verbose_name='Created')),
                ('public', models.BooleanField(db_index=True, default=False, verbose_name='Publicated')),
                ('closed', models.BooleanField(db_index=True, default=False, help_text='If topic is closed, users can not create messages', verbose_name='Closed')),
                ('deleted', models.BooleanField(db_index=True, default=False, verbose_name='Deleted')),
                ('forum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forum.Forum')),
            ],
            options={
                'ordering': ['-id'],
                'permissions': (('can_view_articles', 'Can view topic articles'), ('can_add_articles', 'Can add articles in topic'), ('can_change_articles', 'Can change articles in topic'), ('can_delete_articles', 'Can delete articles from topic'), ('can_hide_articles', 'Can hide articles in topic'), ('can_publish_own_articles', 'Can publish own articles in topic')),
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text='Maximum 10000 simbols', max_length=10000, verbose_name='Text of message')),
                ('created', models.DateTimeField(db_index=True, default=datetime.datetime.now, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Created')),
                ('public', models.BooleanField(db_index=True, default=False, verbose_name='Publicated')),
                ('deleted', models.BooleanField(db_index=True, default=False, verbose_name='Deleted')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Author')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forum.Topic')),
            ],
            options={
                'ordering': ['created'],
            },
        ),
    ]
