# Generated by Django 3.0.4 on 2020-03-20 12:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserOrderTimes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_time', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Время заказа')),
                ('order_manager_id', models.CharField(db_index=True, max_length=32, verbose_name='Идентификатор организации')),
                ('order_type', models.CharField(db_index=True, max_length=16, verbose_name='Тип заказа')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
