# Generated by Django 3.0.4 on 2020-04-10 19:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text='Внимание! Последующее редактирование поля slug невозможно!', max_length=255, verbose_name='Slug')),
                ('url_path', models.CharField(db_index=True, max_length=1500)),
                ('public', models.BooleanField(db_index=True, default=False, help_text='Публиковать страницу могут только пользователи с правами публикации страниц', verbose_name='Опубликована?')),
                ('show_children', models.BooleanField(default=False, verbose_name='Показывать меню подстраниц')),
                ('show_neighbors', models.BooleanField(default=False, verbose_name='Показывать меню соедних страниц')),
                ('create_date', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='pages.Page', verbose_name='Родительская страница')),
            ],
            options={
                'ordering': ['-create_date'],
                'permissions': (('public_page', 'Can public page'),),
            },
        ),
        migrations.CreateModel(
            name='ViewLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.Page')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(choices=[('ru', 'Russian')], db_index=True, max_length=2, verbose_name='Язык')),
                ('title', models.CharField(max_length=512, verbose_name='Заглавие')),
                ('meta', models.CharField(blank=True, help_text='Укажите ключевые слова для страницы', max_length=512, verbose_name='Meta keywords')),
                ('meta_description', models.CharField(blank=True, help_text='Краткое описаие страницы', max_length=512, verbose_name='Meta description')),
                ('content', models.TextField(verbose_name='Контент')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.Page', verbose_name='Родительская страница')),
            ],
            options={
                'unique_together': {('page', 'lang')},
            },
        ),
    ]
