# Generated by Django 3.0.5 on 2021-04-16 21:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sc', models.UUIDField(db_index=True)),
                ('ip', models.GenericIPAddressField()),
                ('user_id', models.CharField(blank=True, max_length=64)),
                ('action', models.CharField(blank=True, db_index=True, max_length=128)),
                ('json_attributes', models.TextField(blank=True, max_length=10240)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
        ),
    ]
